name: landing_page
description: Flutter Portugal Website
publish_to: 'none'
version: 1.2.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  material_color_utilities: ^0.11.1
  mesh: ^0.4.1
  responsive_framework: ^1.1.0
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/flutter_pt_hz.png
    - images/flutter_pt.png
